name: "Prepare Java"
description: "Install Java and cache Maven dependencies"

runs:
  using: "composite"
  steps:
    - name: Build | Setup OpenJDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Build | Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
